# Navigation
nav:
  - Uvicore: index.md
  - Features: features/index.md
  - Getting Started:
    - getting-started/installation.md
    - getting-started/directory-structure.md
    - getting-started/configuration.md
    - getting-started/deployment.md
  - HTTP:
    - http/index.md
    - API:
      - http/api/routing.md
      - http/api/model-router.md
      - http/api/file-upload.md
    - Web:
      - http/web/routing.md
      - http/web/views.md
      - http/web/controllers.md
    - Exceptions:
      - http/exceptions/concepts.md
      - http/exceptions/handlers.md
      - http/exceptions/http-exception.md
      - http/exceptions/not-found.md
      - http/exceptions/permission-denied.md
      - http/exceptions/not-authenticated.md
      - http/exceptions/invalid-credentials.md
  - CLI:
    - cli/index.md
    - cli/commands.md
    - cli/writing-commands.md
    - cli/python-entrypoints.md
  - Database:
    - database/config.md
    - database/tables.md
    - database/queries.md
    - database/orm-basics.md
    - database/orm-model.md
    - database/orm-querybuilder.md
    - database/orm-pydantic.md
  - Architecture:
    - service-providers.md
    - ioc.md
    - request-lifecycle.md
    - bootstrap.md
  - Digging Deeper:
    - events.md
    - jobs.md
    - cache.md
    - mail.md
    - auto-api.md
    - superdict.md
    - cli-entrypoints.md
  - Epologue:
    - release-notes.md
    - mkdocs-help.md







site_name: Uvicore - Fullstack Async Python
site_description: The Fullstack Async Web, API and CLI Python Framework
site_url: https://uvicore.io
#copyright: Copyright 2024 Matthew Reschke

# Repository
repo_name: uvicore/framework
repo_url: https://github.com/uvicore/framework
edit_uri: ''

# Serving
dev_addr: '0.0.0.0:8034'


# Plugins
plugins:
  search: null
  # - tags Nah


# Markdown Extensions
markdown_extensions:
  extra: null
  admonition: null
  pymdownx.superfences: null
  pymdownx.details: null
  pymdownx.tabbed: null
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.tasklist:
    custom_checkbox: true
  footnotes: null
  attr_list: null
  md_in_html: null
  codehilite: null
  markdown.extensions.codehilite:
    guess_lang: false
      #use_pygments: true
      #noclasses: true
  meta: null
  # nl2br: null
  sane_lists: null
  toc:
    permalink: true


# Theme and Colors
theme:
  name: material
  palette:
    scheme: slate  # default or slate
    primary: blue
    accent: purple

  # Palette toggle is for Insiders only (paid)
  # - scheme: default  # default or slate
  #   primary: blue
  #   accent: purple
  #   toggle:
  #     icon: material/lightbulb-outline
  #     name: Light Theme
  # - scheme: slate
  #   primary: blue
  #   accent: purple
  #   toggle:
  #     icon: material/lightbulb-outline
  #     name: Dark Mode
  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  features:
    #- navigation.instant
    - navigation.tabs
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/github
extra_css:
  #- style-dark.css # Set pygments_style: monokai
  #- style-light.css # Comment out pygments_style
  - files/style.css
extra_javascript:
  - files/custom.js

# Extra CSS and Javascript
#extra_css:
#- assets/css/termynal.css
#- assets/css/custom.css
#extra_javascript:
#- assets/js/termynal.js
#- assets/js/custom.js
